@echo off
echo --- Tact Target Website Publisher (Windows) ---
echo Pulling latest files...
git pull
echo Adding updated files...
git add .
echo Committing updates...
git commit -m "Update site content"
echo Pushing updates to GitHub...
git push
echo Site updated successfully!
pause
